### PR TITLE
Migrate to 1.18.2

### PR DESCRIPTION
**Pull request by Aleksey-Terzi**
1. Migrate to 1.18.2
2. Change reference from Spigot to Paper
3. Change from Maven to CivGradle
4. Upgraded support of latest Civ plugins
5. Removed reference to Orebfuscator since "apply physics" fixes visual glitch issue
6. Add a new settings value **Settings.HorizontalLinkDisabled**.

Notes about **Settings.HorizontalLinkDisabled**:
- **False** by default
- Do not block the creation of simple horizontal links, i.e. such that have distance = 1

### CODE REVIEW

**Comment by wingzero54** [comment]
This has conflicts and cannot be merged, I'm assuming it's from Diet's updates to 1.16 that was on our branch and not yours

**Comment by Aleksey-Terzi** [comment]
I've used my original branch as a basis for the migration because it's easier to fix my own bugs than others.

Basically CG is the same as the original version which didn't use NMS and therefore, in general, is independent of MC version.
I've adjusted it to be compatible with current Civ mods and started using BlockData (serialized to string) to store blocks instead of ID and Meta.

What is expected from me?

**Comment by Diet-Cola** [comment]
Probably best to force push over my stuff

**Comment by Aleksey-Terzi** [comment]
Done, thanks

**Pull request closed without merging**
